[package]
name = "category_macro"
version = "0.1.0"
edition.workspace = true

[dependencies]
syn = "2.0"
lotto.workspace = true
quote = "1.0.9"
proc-macro2 = "1.0.24"
convert_case = "0.7.1"

[lib]
proc-macro = true    
