name: Build and test Lotto
on: [push]
env:
  RUST_VERSION: 1.82
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/open-s4c/lotto/core-ci:latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - build: x86-gcc
          cc: gcc
          cxx: g++
          opts: -DLOTTO_RUST=ON
        - build: x86-clang
          cc: clang
          cxx: clang++
          opts: -DLOTTO_RUST=ON -DLOTTO_RACKET_TESTS=ON
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Prepare Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Configure project
        run: cmake -Bbuild -DCMAKE_C_COMPILER=${{ matrix.cfg.cc }}
                           -DCMAKE_CXX_COMPILER=${{ matrix.cfg.cxx }}
                           ${{ matrix.cfg.opts }}
      - name: Build Dice library
        run: cmake --build build --target dice -j
      - name: Build Lotto
        run: cmake --build build -j
      - name: Prepare tarball
        run: tar cvf lotto.tar .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: lotto.tar
          name: lotto-${{ matrix.cfg.build }}
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/open-s4c/lotto/core-ci:latest
    strategy:
      fail-fast: false
      matrix:
        build: [x86-gcc, x86-clang]
        target: [test, tikl-test] #, rust-test]
    needs: build
    steps:
      #- name: Checkout repository once more
      #  uses: actions/checkout@v4
      #  with:
      #    submodules: recursive
      #- name: Prepare Rust toolchain
      #  uses: actions-rust-lang/setup-rust-toolchain@v1
      #  with:
      #    toolchain: ${{ env.RUST_VERSION }}
      - run: ls
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          path: .
          name: lotto-${{ matrix.build }}
      - name: Extract tarball
        run: tar xvf lotto.tar
      - run: ls
      - name: Run tests
        run: cmake --build build --target ${{ matrix.target }}
