name: Build and test Lotto
on: [push]
env:
  RUST_VERSION: 1.82
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/open-s4c/lotto/core-ci:latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - build: x86-gcc
          cc: gcc
          cxx: g++
          opts: -DLOTTO_RUST=OFF
        #- build: x86-clang
        #  cc: clang
        #  cxx: clang++
        #  opts: -DLOTTO_RUST=ON -DLOTTO_RACKET_TESTS=ON
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - run: cmake -Bbuild -DCMAKE_C_COMPILER=${{ matrix.cfg.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.cfg.cxx }} ${{ matrix.cfg.opts }}
      - run: cmake --build build -j
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build
          name: lotto-${{ matrix.cfg.build }}
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/open-s4c/lotto/core-ci:latest
    strategy:
      fail-fast: false
      matrix:
        build: [x86-gcc] #, x86-clang]
        target: [test, lit-crep, lit-daily, lit-pattern-fast] #, rust-test]
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: lotto-${{ matrix.build }}
      - run: cmake --build build --target ${{ matrix.target }}
