name: Build and test Lotto with LTO
on: [push]
env:
  RUST_VERSION: 1.82
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/open-s4c/lotto/core-ci:latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - cc: gcc
          cxx: g++
        - cc: clang
          cxx: clang++
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Prepare Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - name: Configure project
        run: cmake -Bbuild -DCMAKE_C_COMPILER=${{ matrix.cfg.cc }}
                           -DCMAKE_CXX_COMPILER=${{ matrix.cfg.cxx }}
                           -DLOTTO_RUST=off -DLOTTO_LTO=on
      - name: Build Dice library
        run: cmake --build build --target dice -j
      - name: Build Lotto
        run: cmake --build build -j
      - name: Run tests
        run: cmake --build build --target test -j
                                 --target tikl-test
